[pytest]
testpaths =
    pytest_playwright
norecursedirs =
    venv*
    .venv
    env
    .env
    __pycache__
    build
    dist
addopts =
    --html=report.html
    --self-contained-html
    --tb=short
